# Generated by Django 2.2.28 on 2022-06-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='fix_me'),
            preserve_default=False,
        ),
    ]
